## Recalls

In [1]:
# Example
import numpy as np

# 1. Vector Addition
def vector_addition(u, v):
    return np.add(u, v)

# 2. Vector Subtraction
def vector_subtraction(u, v):
    return np.subtract(u, v)

# 3. Scalar-Vector Multiplication
def scalar_vector_multiplication(scalar, v):
    return scalar * v

# 4. Matrix Addition
def matrix_addition(A, B):
    return np.add(A, B)

# 5. Matrix Subtraction
def matrix_subtraction(A, B):
    return np.subtract(A, B)

# 6. Scalar-Matrix Multiplication
def scalar_matrix_multiplication(scalar, A):
    return scalar * A

# 7. Transpose of a Matrix
def matrix_transpose(A):
    return A.T

# 8. Inverse of a Matrix
def matrix_inverse(A):
    return np.linalg.inv(A)

# 9. Determinant of a Matrix
def matrix_determinant(A):
    return np.linalg.det(A)

# 10. Eigenvalues and Eigenvectors of a Matrix
def matrix_eigen(A):
    eigenvalues, eigenvectors = np.linalg.eig(A)
    return eigenvalues, eigenvectors

# 11. Singular Value Decomposition (SVD) of a Matrix
def matrix_svd(A):
    U, S, V = np.linalg.svd(A)
    return U, S, V

##### Creation
Vectors and matrices in Python can be defined manually using Numpy arrays:

In [ ]:
# Define a vector
v = np.array([4, 6, -1])
print(v)

[ 4  6 -1]


In [ ]:
# Dimension
print(v.shape)

# Number of elements
print(v.size)

(3,)
3


In [ ]:
# Define a matrix
M = np.array([[1, 3, 7], [8, 4, 5]])
print(M)

[[1 3 7]
 [8 4 5]]


In [ ]:
# Dimension
print(M.shape)

(2, 3)


In [ ]:
# Number of elements
print(M.size)

6


In [ ]:
# Type of elements
M.dtype

dtype('int64')

The type can be changed a posteriori using ```asarray```:

In [ ]:
M = M.astype('int32')
M.dtype

dtype('int32')

The type can be set when creating the matrix:

In [ ]:
M = np.array([[1, 3, 7], [8, 4, 5]], dtype='int32')
M.dtype

dtype('int32')

##### Creation using numpy functions

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Null matrix of shape (3,3)
Z = np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# A Matrix filled with 1
L = np.ones((2,3))
print(L)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Identity matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Diagonal matrix
D = np.diag([2, -1, 3])
print(D)

[[ 2  0  0]
 [ 0 -1  0]
 [ 0  0  3]]


##### Reshaping

In [ ]:
x = np.arange(1,10)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Reshape
x.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Reshape creates a new reshaped object
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Resize reshapes inplace
x.resize((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Reshapes to the initial dimension
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# ravel and flaten do not modify the array (not inplace)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Concatenation

In [ ]:
M = np.array([[1, 2], [3, 4]])
print(M)

[[1 2]
 [3 4]]


In [ ]:
N = np.array([[5, 6], [7, 8]])
print(N)

[[5 6]
 [7 8]]


In [ ]:
# Concatenate M and N vertically
print(np.concatenate((M, N)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Concatenate M and N horizontally
print(np.concatenate((M, N), axis=1))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# Another way to concatenate vertically
print(np.vstack((M,N)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Another way to concatenate horizontally
print(np.hstack((M,N)))

[[1 2 5 6]
 [3 4 7 8]]


#### Inexing and slicing

One dimensional numpy arrays can be sliced exactly as a list (Check TP0 for details).

In [ ]:
M = np.array([[4,2,-2],[1,0,1],[6,-4,3]])
print(M)

[[ 4  2 -2]
 [ 1  0  1]
 [ 6 -4  3]]


In [ ]:
# Access to a specific items
print(M[0,0])
print(M[1,2])

4
1


In [ ]:
# Another way to access to items
print(M[0][0])
print(M[1][2])

4
1


In [ ]:
# Access to a specific line
print(M[0,:])

[ 4  2 -2]


In [ ]:
# Access to a specific column
print(M[:,0])

[4 1 6]


In [ ]:
# Access to a specific bloc
print(M[1:,1:])

array([[ 0,  1],
       [-4,  3]])

In [ ]:
# Logical mask
print(M < 2)

[[False False  True]
 [ True  True  True]
 [False  True False]]


#### Algebraic operations

In [ ]:
# Vectors definitions
x = np.array([1, 3])
y = np.array([4, 2])

# Matrices definitions
M = np.array([[1, -5], [-1, 4]])
N = np.array([[2, 1], [-4, 6]])

In [ ]:
# Vector addition
print(x+y)

[5 5]


In [ ]:
# Matrix addition
print(M+N)

[[ 3 -4]
 [-5 10]]


In [ ]:
# Another way to perform addition (true fro both vectors and matrices)
print(np.add(M,N))

[[ 3 -4]
 [-5 10]]


In [ ]:
# Subtraction
print(M-N)

[[-1 -6]
 [ 3 -2]]


In [ ]:
# Another way to perform substraction
print(np.subtract(M,N))

[[-1 -6]
 [ 3 -2]]


In [ ]:
# Element wise product
print(M*N)

[[ 2 -5]
 [ 4 24]]


In [ ]:
# Power (element wise power)
print(M**2)

[[ 1 25]
 [ 1 16]]


In [ ]:
# Dot product
x.dot(y)

10

In [ ]:
# Matrix product
print(M @ N)

[[ 22 -29]
 [-18  23]]


In [ ]:
# Another way to perform matrix product
print(M.dot(N))

[[ 22 -29]
 [-18  23]]


In [ ]:
# Matrix vector product
print(M @ x)

[-14  11]


In [ ]:
# Another way to perform matrix vector product
print(M.dot(x))

[-14  11]


## Exercices

### Exercice 1

1. Create a matrix A and B of shape (5, 10), and a vector C of size 10, using the randn function from numpy.

In [8]:
# Answer
matrix_A = np.random.randn(5,10)

matrix_B = np.random.randn(5,10)

vector_C = np.array(np.random.rand(10))

print(matrix_A)
print("----------------------Matrice A--------------------------")
print(matrix_B)
print("----------------------Matrice B--------------------------")
print(vector_C)
print("----------------------VECTOR C---------------------------")

[[ 0.5584855   0.22276537 -0.81089689 -0.983431   -0.14662541 -1.09033551
   0.37825634 -0.10138673 -0.17664155  0.97548259]
 [-0.56789684 -0.67546298 -0.32220987 -1.28547912 -1.10279891 -1.3602319
   0.94022293  0.32880736  0.19359986  0.11628254]
 [ 2.70405594 -0.09428417  0.53967784 -0.03363454 -0.71272055  0.46162342
  -1.15242503  0.8618742  -0.87430536 -2.52227764]
 [ 1.45252341 -0.12122169  0.25265176 -0.33424228 -0.01312421  0.2510255
   0.47325187  0.56236076  0.93415869 -0.42912064]
 [ 0.09054557 -0.4289761  -1.04188778 -1.25081388 -1.59143181  0.39282381
   0.62059373  0.24697846  0.17801198  0.83673107]]
----------------------Matrice A--------------------------
[[ 0.0601708   0.86757327 -0.10282391  0.00961362  0.91359762 -0.23359674
   0.31622313 -0.3572523  -0.44976105 -1.46306631]
 [ 1.45969099  1.17506429  0.86945646 -0.27194628 -1.83254001 -1.47988082
   0.28158662  0.77550992  0.99771907  0.85996011]
 [-1.42794928 -1.36394364  1.31250076  1.21479036  0.17353167 -2.101

2. Compute the sum D and the subtraction F of matrices A and B. What is the shape of the obtained matrices?

In [10]:
# Answer
sum_D = matrix_addition(matrix_A, matrix_B)
#np.add(a,b)
print(sum_D)
print("----------------------SUM D--------------------------")

substraction_F = matrix_addition(matrix_A, matrix_B)
#np.substract(a,b)
print(substraction_F)
print("----------------------SUM F--------------------------")

[[ 0.6186563   1.09033864 -0.9137208  -0.97381739  0.76697221 -1.32393225
   0.69447946 -0.45863903 -0.6264026  -0.48758372]
 [ 0.89179416  0.49960131  0.54724659 -1.5574254  -2.93533892 -2.84011272
   1.22180954  1.10431728  1.19131893  0.97624265]
 [ 1.27610665 -1.45822781  1.85217859  1.18115582 -0.53918888 -1.63937976
  -0.8049061   0.81010916 -0.60222938 -3.02445307]
 [ 0.89883027 -0.38515628 -1.16234191  0.06732229  0.20004661 -1.32012241
  -0.77124303  1.578295    0.9146096   0.41193689]
 [-0.21809708 -0.56904891  0.39644658 -0.79269344 -1.16842574 -1.33656302
   1.63053759 -1.29062798  0.1187034   1.58855369]]
----------------------SUM D--------------------------
[[ 0.6186563   1.09033864 -0.9137208  -0.97381739  0.76697221 -1.32393225
   0.69447946 -0.45863903 -0.6264026  -0.48758372]
 [ 0.89179416  0.49960131  0.54724659 -1.5574254  -2.93533892 -2.84011272
   1.22180954  1.10431728  1.19131893  0.97624265]
 [ 1.27610665 -1.45822781  1.85217859  1.18115582 -0.53918888 -1.63937

3. Compute the product of λ=10 and the vector C. What is the dimension of λC?

In [12]:
# Answer
lc = scalar_vector_multiplication(10, vector_C)
print(lc)
print("----------------------Product of l and vector C--------------------------")
print(lc.shape)
print("----------------------LC Dimension--------------------------")

[0.02731497 2.61432703 7.36013232 3.19245869 6.42761094 3.24191286
 0.9329147  3.13216977 5.77841072 4.71951605]
----------------------Product of l and vector C--------------------------
(10,)
----------------------LC Dimension--------------------------


4. Calculate the sum and the element-wise multiplication between C and F. What is the dimension of the outputs?

In [14]:
# Answer
G = vector_C * substraction_F
print(G)
print("----------------------element wise multiplication--------------------------")
GG = np.add(vector_C, substraction_F)
print(GG)
print("----------------------sum--------------------------")

[[ 1.68985773e-03  2.85050178e-01 -6.72510602e-01 -3.10887179e-01
   4.92979897e-01 -4.29207300e-01  6.47890099e-02 -1.43653530e-01
  -3.61961150e-01 -2.30115918e-01]
 [ 2.43593292e-03  1.30612121e-01  4.02780734e-01 -4.97201625e-01
  -1.88672165e+00 -9.20739794e-01  1.13984408e-01  3.45890919e-01
   6.88393008e-01  4.60739287e-01]
 [ 3.48568129e-03 -3.81228438e-01  1.36322795e+00  3.77079117e-01
  -3.46569636e-01 -5.31472632e-01 -7.50908733e-02  2.53739943e-01
  -3.47992873e-01 -1.42739548e+00]
 [ 2.45515204e-03 -1.00692448e-01 -8.55499023e-01  2.14923639e-02
   1.28582178e-01 -4.27972181e-01 -7.19503955e-02  4.94348790e-01
   5.28498990e-01  1.94414277e-01]
 [-5.95731492e-04 -1.48767995e-01  2.91789927e-01 -2.53064106e-01
  -7.51018606e-01 -4.33302084e-01  1.52115248e-01 -4.04246596e-01
   6.85917005e-02  7.49720465e-01]]
----------------------element wise multiplication--------------------------
[[ 0.6213878   1.35177134 -0.17770757 -0.65457152  1.4097333  -0.99974097
   0.78777093 

5. Calculate G, the dot product between C and F, and give the dimension of G. What is the difference between dot product and multiplication of vectors?

In [ ]:
# Answer
I = substraction_F.dot

In [ ]:
help()

Streaming output truncated to the last 5000 lines.
        
        Returns
        -------
        angle : ndarray
            Array of angles in radians, in the range ``[-pi, pi]``.
            This is a scalar if both `x1` and `x2` are scalars.
        
        See Also
        --------
        arctan, tan, angle
        
        Notes
        -----
        *arctan2* is identical to the `atan2` function of the underlying
        C library.  The following special values are defined in the C
        standard: [1]_
        
        ====== ====== ================
        `x1`   `x2`   `arctan2(x1,x2)`
        ====== ====== ================
        +/- 0  +0     +/- 0
        +/- 0  -0     +/- pi
         > 0   +/-inf +0 / +pi
         < 0   +/-inf -0 / -pi
        +/-inf +inf   +/- (pi/4)
        +/-inf -inf   +/- (3*pi/4)
        ====== ====== ================
        
        Note that +0 and -0 are distinct floating point numbers, as are +inf
        and -inf.
        
        Refere

6. Calculate the sum and multiplication between F and B. Give the dimension of each result.

In [ ]:
# Answer

7. Calculate the dot product between B and F (in this order). Give the dimension of the result.

In [ ]:
# Answer

8. Calculate the dot product between F and B (in this order). If it works, give the dimension of the result; else propose a solution, and give the dimension of the result.

In [ ]:
# Answer

9. Calculate I the dot product between A and B. Give the dimension of I.

In [ ]:
# Answer

10. Give the detiminant of I.

In [ ]:
# Answer

11. Give J the Inverse of I, if I is inversible.

In [ ]:
# Answer

12. Decompose the matrix I using eigendecomposition method.

In [ ]:
# Answer

13. Decompose the matrix I using svd method

In [ ]:
# Answer

### Exercice 2: Power iteration method

The objective of this excercice is to compute the eigenvector of a matrix associated to its largest eigenvector using the power iteration method: Given a squared matrix $A$ of shape $n\times n$ and a vector $x_0\in\mathbb{R}^n$, then the sequence of vectors $(x_k)_{k\in\mathbb{N}}$ defined as:
$$
x_{k+1}=\frac{Ax_k}{\Vert A x_k\Vert},
$$
converges to the largest eigenvector in absolute value (we admit this result).
  

1. Define a function ```power_iteration(A, x0, k)``` that returns $x_k$.



In [ ]:
# Answer


2. Using the function ```power_iteration```, compute the largest eigenvector of the matrix
$$
A = \begin{bmatrix} 0.5 & 0.5\\ 0.2 & 0.8 \end{bmatrix}
$$

In [ ]:
# Answer


3. Compute the eigen value associated to this vector.
***Indication:*** If $v$ is a normalized eigenvector of $A$, then its associated eigenvalue is given by $λ=Av⋅v$

In [ ]:
# Answer


4. Adapt the function ```power_iteration``` such that it allows to compute the largest eigenvalue with its associated eigenvector of a matrix given precision value.

In [ ]:
# Answer


5. Compare the execution times of the previous script and the numpy function for matrices of shape $n\times n$ with $n\in \{10, 100, 1000\}$   

In [ ]:
# Answer


### Exercice 3

Let $A$ be a matrix and $b$ a vector defined by:

```
M = np.random.randn(3, 3)
A = M + M.T
b = np.random.rand(3)
```



Solve the linear system $Ax=b$ with two different methods

### Exercise 4


Write a Python program that performs the following tasks:

1. Generate a random vector in 3D space.<br>
2. Choose a target subspace by specifying a basis (orthonormal vectors) for the subspace.<br>
3. Project the random vector onto the target subspace to find its orthogonal projection.<br>
4. Calculate the residual vector as the difference between the original vector and its projection.<br>
5. Verify that the projection and residual vectors are orthogonal.

### Exercice 4: Orthogonal Projections



The objectif of the exercice is to compute the orthogonal projection of a vector into a given subspace. We let be $x\in \mathbb{R}^{n}$, $E\subset\mathbb{R}^{n}$ a subspace of dimension $p$, and $B=\{e_1, ⋯,e_{p} \}$ an orthonormal basis of $E$. Then, the orthogonal projection of the vector $x$ on $E$ is given by
$$
p_E(x) = \sum_{i=1}^{p} <x,e_i>e_i
$$

In a more general case, given the matrix $A$ the projection matrix is given by
$$
P = A(A^tA)^{-1}A^t
$$
The projection matrix verifies the following properties:


1.   $P$ is a squared matrix.
2.   Symmetry $P^t=P$.
3.   $P$ is idempotent: $P^2= P$.


1. Define a function ```is_orthonormal(A)``` that takes as parameters the matrix $A$ of wich the columns corresponds to the basis vectors of the target subspace and returns  ```True``` if the basis is orthonormal ```False``` otherwise.

In [ ]:
# Answer


2. Define a function ```project(B,x)``` that takes as parameters a vector $x\in \mathbb{R}^{n}$ and ```B``` a list of vectors of the basis $B$.

In [ ]:
# Answer


3. Let $E$ the subspace spanned by the basis $B = \left\{\left(\frac{1}{\sqrt{2}},\frac{1}{\sqrt{2}},0\right)^t,\left(\frac{1}{\sqrt{3}},-\frac{1}{\sqrt{3}},\frac{1}{\sqrt{3}}\right)^t\right\}$. Verify that the basis is orthonormal.

In [ ]:
# Answer


4. Generate a three dimensional vector (i.e., n=3). And compute its projection on $E$.  

In [ ]:
# Answer


5. Let be $E$ the subspace spanned by $B=\left\{ (0,1,1)^t,(1,-1,1)^t \right\}$, and $x=(1,2,-1)^t$. Compute the projection matrix $P$ and verify numerically that it satisfies the three properties listed above.

In [ ]:
# Answer


6. Compute the projection of $x$ on $E$.

In [ ]:
# Answer


### Exercise 5: Diagonalization of symmetric Matrices


The objective of this exercice is to omplement a Python program that demonstrates the diagonalization of a symmetric matrix:

1. Generate a random symmetric matrix of a specified size.<br>



In [ ]:
# Answer


2. Compute the eigenvalues and eigenvectors of the symmetric matrix.

In [ ]:
# Answer


3. Verify that the eigenvectors are orthogonal.

In [ ]:
# Answer


4. Construct a diagonal matrix using the eigenvalues.

In [ ]:
# Answer


5. Reconstruct the original matrix using eigenvectors and the diagonal matrix.

In [ ]:
# Answer


### Exercise 6:
1. Define a class Squared_matrix that inherits from the class ```np.matrix``` with the attribute values which corresponds to the squared matrix, and a constructor that instanciates the classe (it should return an error message if the matrix is not squared) and an ```__str()__``` that prints the matrix.

In [ ]:
# Answer


2. Define a method:
* ```rank()``` that returns the rank of the matrix.  
* ```is_invertible```that returns a boolean (```True``` if the matrix is invertible ```False``` otherwise).
* ```inverse()``` that returns the inverse of the matrix when possible.
* ```eigenvalues()``` and ```eigenvectors``` that return the eigenvalues and eigenvectors of the matrix.

In [ ]:
# Answer


3. Given a squared matrix $A$, we recall the definition of some norms:

$$
\begin{align*}
&||A||_F \, = \sqrt{\sum_{i=1}^n\sum_{j=1}^n a^2_{i,j}} = \sqrt{tr(A^tA)},  \\
&||A||_1 \,\, = \max_{1\leq j\leq n} \sum_{i=1}^{n}|a_{i,j}|, \\
&||A||_2 \,\, = \sqrt{\rho(A^tA)}, \\
&||A||_\infty = \max_{1\leq i\leq n} \sum_{j=1}^{n}|a_{i,j}|,
\end{align*}
$$
where $\rho(\cdot)$ design the spectral radius, i.e., the largest (in absolute value) eigenvalue of a matrix. Define the method ```norm_f(ind)``` that returns the norm given the indice ```ind``` (the indice is a string with possible values: ```"F"```,```"1"```,```"2"```, and ```"inf"```).


In [ ]:
# Answer
